Traceback (most recent call last):
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df.plot(color="green");
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/x6/ffnr59f116l96_y0q0bjfz7c0000gn/T/ipykernel_53231/3960458575.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mdf[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mcolor[0m[0;34m=[0m[0;34m"green"[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/opt/anaconda3/lib/python3.7/site-packages/geopandas/geodataframe.py[0m in [0;36mplot[0;34m(self, *args, **kwargs)[0m
[1;32m    919[0m         [0;32mfrom[0m [0mthere[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m    920[0m         """
[0;32m--> 921[0;31m         [0;32mreturn[0m [0mplot_dataframe[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    922[0m [0;34m[0m[0m
[1;32m    923[0m     [0mplot[0m[0;34m.[0m[0m__doc__[0m [0;34m=[0m [0mplot_dataframe[0m[0;34m.[0m[0m__doc__[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/geopandas/plotting.py[0m in [0;36mplot_dataframe[0;34m(df, column, cmap, color, ax, cax, categorical, legend, scheme, k, vmin, vmax, markersize, figsize, legend_kwds, categories, classification_kwds, missing_kwds, aspect, **style_kwds)[0m
[1;32m    621[0m             [0mmarkersize[0m[0;34m=[0m[0mmarkersize[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    622[0m             [0maspect[0m[0;34m=[0m[0maspect[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 623[0;31m             [0;34m**[0m[0mstyle_kwds[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    624[0m         )
[1;32m    625[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/geopandas/plotting.py[0m in [0;36mplot_series[0;34m(s, cmap, color, ax, figsize, aspect, **style_kwds)[0m
[1;32m    388[0m [0;34m[0m[0m
[1;32m    389[0m     [0;31m# decompose GeometryCollections[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 390[0;31m     [0mgeoms[0m[0;34m,[0m [0mmultiindex[0m [0;34m=[0m [0m_flatten_multi_geoms[0m[0;34m([0m[0ms[0m[0;34m.[0m[0mgeometry[0m[0;34m,[0m [0mprefix[0m[0;34m=[0m[0;34m"Geom"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    391[0m     [0mvalues[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mtake[0m[0;34m([0m[0mvalues[0m[0;34m,[0m [0mmultiindex[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m [0;32mif[0m [0mcmap[0m [0;32melse[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m    392[0m     [0mexpl_series[0m [0;34m=[0m [0mgeopandas[0m[0;34m.[0m[0mGeoSeries[0m[0;34m([0m[0mgeoms[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/geopandas/plotting.py[0m in [0;36m_flatten_multi_geoms[0;34m(geoms, prefix)[0m
[1;32m     42[0m     [0mcomponents[0m[0;34m,[0m [0mcomponent_index[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m,[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     43[0m [0;34m[0m[0m
[0;32m---> 44[0;31m     [0;32mif[0m [0;32mnot[0m [0mgeoms[0m[0;34m.[0m[0mgeom_type[0m[0;34m.[0m[0mstr[0m[0;34m.[0m[0mstartswith[0m[0;34m([0m[0mprefix[0m[0;34m)[0m[0;34m.[0m[0many[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     45[0m         [0;32mreturn[0m [0mgeoms[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0marange[0m[0;34m([0m[0mlen[0m[0;34m([0m[0mgeoms[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     46[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/strings/accessor.py[0m in [0;36mwrapper[0;34m(self, *args, **kwargs)[0m
[1;32m     99[0m                 )
[1;32m    100[0m                 [0;32mraise[0m [0mTypeError[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 101[0;31m             [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    102[0m [0;34m[0m[0m
[1;32m    103[0m         [0mwrapper[0m[0;34m.[0m[0m__name__[0m [0;34m=[0m [0mfunc_name[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/strings/accessor.py[0m in [0;36mstartswith[0;34m(self, pat, na)[0m
[1;32m   2069[0m         [0mdtype[0m[0;34m:[0m [0mbool[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2070[0m         """
[0;32m-> 2071[0;31m         [0mresult[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_data[0m[0;34m.[0m[0marray[0m[0;34m.[0m[0m_str_startswith[0m[0;34m([0m[0mpat[0m[0;34m,[0m [0mna[0m[0;34m=[0m[0mna[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2072[0m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_wrap_result[0m[0;34m([0m[0mresult[0m[0;34m,[0m [0mreturns_string[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2073[0m [0;34m[0m[0m

[0;31mAttributeError[0m: 'PandasArray' object has no attribute '_str_startswith'
AttributeError: 'PandasArray' object has no attribute '_str_startswith'

