Traceback (most recent call last):
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xf = pd.DataFrame()

fig, ax = plt.subplots()
xf.resample("D").asfreq().plot(ax=ax)
xf.resample("D").interpolate(method="poly", limit_direction="forward").plot(ax=ax);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-21-5c8fc53c80ce>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mfig[0m[0;34m,[0m [0max[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0msubplots[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mxf[0m[0;34m.[0m[0mresample[0m[0;34m([0m[0;34m"D"[0m[0;34m)[0m[0;34m.[0m[0masfreq[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0max[0m[0;34m=[0m[0max[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0mxf[0m[0;34m.[0m[0mresample[0m[0;34m([0m[0;34m"D"[0m[0;34m)[0m[0;34m.[0m[0minterpolate[0m[0;34m([0m[0mmethod[0m[0;34m=[0m[0;34m"poly"[0m[0;34m,[0m [0mlimit_direction[0m[0;34m=[0m[0;34m"forward"[0m[0;34m)[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0max[0m[0;34m=[0m[0max[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py[0m in [0;36mresample[0;34m(self, rule, axis, closed, label, convention, kind, loffset, base, on, level, origin, offset)[0m
[1;32m   8380[0m             [0mlevel[0m[0;34m=[0m[0mlevel[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   8381[0m             [0morigin[0m[0;34m=[0m[0morigin[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 8382[0;31m             [0moffset[0m[0;34m=[0m[0moffset[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   8383[0m         )
[1;32m   8384[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/resample.py[0m in [0;36mget_resampler[0;34m(obj, kind, **kwds)[0m
[1;32m   1309[0m     """
[1;32m   1310[0m     [0mtg[0m [0;34m=[0m [0mTimeGrouper[0m[0;34m([0m[0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1311[0;31m     [0;32mreturn[0m [0mtg[0m[0;34m.[0m[0m_get_resampler[0m[0;34m([0m[0mobj[0m[0;34m,[0m [0mkind[0m[0;34m=[0m[0mkind[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1312[0m [0;34m[0m[0m
[1;32m   1313[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/resample.py[0m in [0;36m_get_resampler[0;34m(self, obj, kind)[0m
[1;32m   1475[0m [0;34m[0m[0m
[1;32m   1476[0m         raise TypeError(
[0;32m-> 1477[0;31m             [0;34m"Only valid with DatetimeIndex, "[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1478[0m             [0;34m"TimedeltaIndex or PeriodIndex, "[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1479[0m             [0;34mf"but got an instance of '{type(ax).__name__}'"[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'

